name: Build

on:
  pull_request:
  push:
    branches-ignore:
      - main

jobs:
  ci:
    name: CI
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork }}
    uses: ./.github/workflows/ci.yml
    with:
      isRelease: false
    secrets: inherit
